class SaveChainInspector
  VERSION: String

  def self.start: (?to: String | _SaveChainInspectorPath | _SaveChainInspectorOutput) { () -> untyped } -> untyped
end

interface _SaveChainInspectorPath
  def to_path: () -> String
end

interface _SaveChainInspectorOutput
  def puts: (*untyped) -> untyped
end
